service: graphity-todo-list

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}

functions:
  home:
    handler: src/handler.home
    events:
      - http:
          path: /
          method: get
          cors: true

  graphql:
    handler: src/handler.graphql
    events:
      - http:
          path: graphql
          method: any
          cors: true
